var data = 
    [{
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1044534,
      "LocalAuthorityBusinessID": "CP18_000225",
      "BusinessName": "Admiral Benbow",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "46 Chapel Street",
      "AddressLine2": "Penzance",
      "AddressLine3": "Cornwall",
      "PostCode": "TR18 4AF",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "13/12/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.534619,
      "Latitude": 50.117316,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 909990,
      "LocalAuthorityBusinessID": "CP16_000701",
      "BusinessName": "Atlantic Way Bude Farmshop",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Atlanticway Bude Farmshop",
      "AddressLine2": "Killock Farm",
      "AddressLine3": "Kilkhampton",
      "PostCode": "EX23 9PZ",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "30/01/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.499954,
      "Latitude": 50.858365,
      "AddressLine4": "Bude",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 445713,
      "LocalAuthorityBusinessID": "C1_PI_000003764",
      "BusinessName": "Balti Curries",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "47 Arwenack Street",
      "AddressLine2": "Falmouth",
      "AddressLine3": "Cornwall",
      "PostCode": "TR11 3JH",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "13/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.065815,
      "Latitude": 50.152101,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1034514,
      "LocalAuthorityBusinessID": "CP18_000131",
      "BusinessName": "Barnaby's",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "Barnabys",
      "AddressLine2": "22A Duke Street",
      "AddressLine3": "Padstow",
      "PostCode": "PL28 8AB",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "04/05/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.9396669,
      "Latitude": 50.5416833,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 457611,
      "LocalAuthorityBusinessID": "E1_1200",
      "BusinessName": "Barneys Restaurant",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "10 Molesworth Street",
      "AddressLine2": "Wadebridge",
      "AddressLine3": "Cornwall",
      "PostCode": "PL27 7DA",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "13/11/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.836078,
      "Latitude": 50.516928,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 554791,
      "LocalAuthorityBusinessID": "C2_233803",
      "BusinessName": "Barrowfield Hotel",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "1 - 5 Hilgrove Road",
      "AddressLine2": "Newquay",
      "AddressLine3": "Cornwall",
      "PostCode": "TR7 2QY",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "22/03/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.068822,
      "Latitude": 50.417485,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 705803,
      "LocalAuthorityBusinessID": "CP14_000940",
      "BusinessName": "Ben And Jerrys",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "8 Central Square",
      "AddressLine2": "Newquay",
      "AddressLine3": "Cornwall",
      "PostCode": "TR7 1JH",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "26/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.086506,
      "Latitude": 50.413158,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 455230,
      "LocalAuthorityBusinessID": "E2_04_00095_MIXED",
      "BusinessName": "Blue Moon Restaurant",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "Blue Moon Traditional Indian Cuisin",
      "AddressLine2": "39 Lower Fore Street",
      "AddressLine3": "Saltash",
      "PostCode": "PL12 6JQ",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "13/06/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.209475994,
      "Latitude": 50.40859604,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 456217,
      "LocalAuthorityBusinessID": "CP12_001043",
      "BusinessName": "Bridge Grill",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "4 Bridgend",
      "AddressLine2": "Fore Street",
      "AddressLine3": "East Looe",
      "PostCode": "PL13 1HH",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "24/10/2017",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": true,
      "Longitude": -4.454841,
      "Latitude": 50.356012,
      "AddressLine4": "Looe",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 534501,
      "LocalAuthorityBusinessID": "CP13_000333",
      "BusinessName": "California Bowl",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "California Bowl At",
      "AddressLine2": "Hotel California",
      "AddressLine3": "32 Pentire Crescent",
      "PostCode": "TR7 1PU",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "01/05/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.102811,
      "Latitude": 50.410187,
      "AddressLine4": "Newquay",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1008341,
      "LocalAuthorityBusinessID": "CP17_000782",
      "BusinessName": "Chapter 8",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "14 Honey Street",
      "AddressLine2": "Bodmin",
      "AddressLine3": "Cornwall",
      "PostCode": "PL31 2DN",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "08/01/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.718305,
      "Latitude": 50.471014,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 748067,
      "LocalAuthorityBusinessID": "CP14_000998",
      "BusinessName": "Chough Bakery (Mother Iveys Shop)",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Mother Iveys Bay Caravan Site",
      "AddressLine2": "Boobys Bay",
      "AddressLine3": "Padstow",
      "PostCode": "PL28 8SL",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "17/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 5,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.01767,
      "Latitude": 50.543284,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1087191,
      "LocalAuthorityBusinessID": "CP18_000882",
      "BusinessName": "Chung Hing",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "Chung Hing Chinese Takeaway",
      "AddressLine2": "11 Southgate Street",
      "AddressLine3": "Launceston",
      "PostCode": "PL15 9DP",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "02/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 20,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.359921932,
      "Latitude": 50.63677216,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1130648,
      "LocalAuthorityBusinessID": "CP19_000304",
      "BusinessName": "Chungs",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "Chungs Chinese Takeaway",
      "AddressLine2": "7 Flexbury Park",
      "AddressLine3": "Flexbury",
      "PostCode": "EX23 8RS",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "14/03/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.542285919,
      "Latitude": 50.83510971,
      "AddressLine4": "Bude",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 690571,
      "LocalAuthorityBusinessID": "CP14_000775",
      "BusinessName": "Church Road Stores",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Church Road",
      "AddressLine2": "Saltash",
      "AddressLine3": "Cornwall",
      "PostCode": "PL12 4EF",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "30/01/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.228338,
      "Latitude": 50.406834,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 809234,
      "LocalAuthorityBusinessID": "CP15_000785",
      "BusinessName": "Clover Market",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "7 High Street",
      "AddressLine2": "Launceston",
      "AddressLine3": "Cornwall",
      "PostCode": "PL15 8ER",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "24/01/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 5,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.360728,
      "Latitude": 50.637339,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1060000,
      "LocalAuthorityBusinessID": "CP18_000511",
      "BusinessName": "College Lane Fish Bar",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "College Lane",
      "AddressLine2": "Bodmin",
      "AddressLine3": "Cornwall",
      "PostCode": "PL31 1HT",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "25/07/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.712655067,
      "Latitude": 50.46144867,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 807020,
      "LocalAuthorityBusinessID": "CP15_000769",
      "BusinessName": "Cornish Stores",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Linleys",
      "AddressLine2": "Penally Hill",
      "AddressLine3": "Boscastle",
      "PostCode": "PL35 0HE",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "01/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.692335,
      "Latitude": 50.689976,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 947453,
      "LocalAuthorityBusinessID": "CP17_000136",
      "BusinessName": "Eagle House Hotel",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "3 Castle Street",
      "AddressLine2": "Launceston",
      "AddressLine3": "Cornwall",
      "PostCode": "PL15 8BA",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "08/02/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.362319,
      "Latitude": 50.638314,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 508129,
      "LocalAuthorityBusinessID": "C1_PI_000006911",
      "BusinessName": "Falmouth Townhouse",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "The Falmouth Townhouse",
      "AddressLine2": "3 Grove Place",
      "AddressLine3": "Falmouth",
      "PostCode": "TR11 4AL",
      "RatingValue": 0,
      "RatingKey": "fhrs_0_en-GB",
      "RatingDate": "03/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 20,
      "Structural": 20,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.064356,
      "Latitude": 50.150952,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 951408,
      "LocalAuthorityBusinessID": "CP17_000180",
      "BusinessName": "Flames",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "32 Fore Street",
      "AddressLine2": "Camelford",
      "AddressLine3": "Cornwall",
      "PostCode": "PL32 9PG",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "18/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": null,
      "Structural": null,
      "ConfidenceInManagement": null,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.679653,
      "Latitude": 50.621486,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 594556,
      "LocalAuthorityBusinessID": "C1_PI_000006907",
      "BusinessName": "Grove Hotel",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "1 Grove Place",
      "AddressLine2": "Falmouth",
      "AddressLine3": "Cornwall",
      "PostCode": "TR11 4AU",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "07/09/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.064513,
      "Latitude": 50.151002,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 965689,
      "LocalAuthorityBusinessID": "CP17_000391",
      "BusinessName": "Halfway House",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "The Halfway House",
      "AddressLine2": "Halfway House",
      "AddressLine3": "Rame Cross",
      "PostCode": "TR10 9ED",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "01/11/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.187058,
      "Latitude": 50.15854,
      "AddressLine4": "Penryn",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 481090,
      "LocalAuthorityBusinessID": "E1_6545",
      "BusinessName": "Hong Kong Island",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "1A Market Place",
      "AddressLine2": "Camelford",
      "AddressLine3": "Cornwall",
      "PostCode": "PL32 9PB",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "13/03/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.678693,
      "Latitude": 50.623244,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1073538,
      "LocalAuthorityBusinessID": "CP18_000726",
      "BusinessName": "Into The Woods",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "West End",
      "AddressLine2": "Pentewan",
      "AddressLine3": "St Austell",
      "PostCode": "PL26 6BX",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "02/11/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 15,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.783704,
      "Latitude": 50.292163,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1096131,
      "LocalAuthorityBusinessID": "CP19_000014",
      "BusinessName": "Kinn Asia",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "27 Arwenack Street",
      "AddressLine2": "Falmouth",
      "AddressLine3": "Cornwall",
      "PostCode": "TR11 3JE",
      "RatingValue": 0,
      "RatingKey": "fhrs_0_en-GB",
      "RatingDate": "05/12/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 30,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.066723,
      "Latitude": 50.152716,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1060007,
      "LocalAuthorityBusinessID": "CP18_000518",
      "BusinessName": "Kitchen \\& Co. Cornwall",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Chester Road Butchers",
      "AddressLine2": "9 Chester Road",
      "AddressLine3": "Newquay",
      "PostCode": "TR7 2RT",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "31/05/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 5,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.064700127,
      "Latitude": 50.41730499,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1069496,
      "LocalAuthorityBusinessID": "CP18_000640",
      "BusinessName": "Level Crossing Refreshments",
      "BusinessType": "Mobile caterer",
      "BusinessTypeID": 7846,
      "AddressLine1": "",
      "AddressLine2": "",
      "AddressLine3": "",
      "PostCode": "",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "21/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 5,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": null,
      "Latitude": null,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1097015,
      "LocalAuthorityBusinessID": "CP19_000024",
      "BusinessName": "Little India",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "Light Of Bengal",
      "AddressLine2": "52 Market Jew Street",
      "AddressLine3": "Penzance",
      "PostCode": "TR18 2HZ",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "06/02/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.533689976,
      "Latitude": 50.12161636,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1034519,
      "LocalAuthorityBusinessID": "CP18_000138",
      "BusinessName": "Minxys",
      "BusinessType": "Mobile caterer",
      "BusinessTypeID": 7846,
      "AddressLine1": "Mobile Catering Unit",
      "AddressLine2": "The Roundhouse Business Park",
      "AddressLine3": "Harbour Road",
      "PostCode": "PL24 2BB",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "09/04/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 5,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.709428,
      "Latitude": 50.350706,
      "AddressLine4": "Par",
      "RightToReply": "&lt;p&gt;\n\tI agree with the inspection results but have since carried out the following improvements:&lt;/p&gt;\n&lt;p&gt;\n\tI have only just opened and didn&amp;#39;t realise the importance of the paperwork being completed. This has now been done.&lt;/p&gt;\n&lt;p&gt;\n\tThe conditions found at the time of the inspection were not typical of the normal conditions maintained at the estalishment and arose because:&lt;/p&gt;\n&lt;p&gt;\n\tAs stated in first inspection, everything is in good order, cleanliness as well wagon itself. Paperwork now confirms all processes are in place&lt;/p&gt;"
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 552418,
      "LocalAuthorityBusinessID": "W2_00000435",
      "BusinessName": "Mothers Traditional Cornish Pasties",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "Mothers",
      "AddressLine2": "34 Coinagehall Street",
      "AddressLine3": "Helston",
      "PostCode": "TR13 8EQ",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "06/11/2017",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.276144981,
      "Latitude": 50.10037231,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 402727,
      "LocalAuthorityBusinessID": "W2_00005134",
      "BusinessName": "Mullion Mini Market",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Nansmellyon Road",
      "AddressLine2": "Mullion",
      "AddressLine3": "Helston",
      "PostCode": "TR12 7DH",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "25/02/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 5,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.245999,
      "Latitude": 50.024177,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 834000,
      "LocalAuthorityBusinessID": "CP15_001021",
      "BusinessName": "Mylor Fish",
      "BusinessType": "Mobile caterer",
      "BusinessTypeID": 7846,
      "AddressLine1": "",
      "AddressLine2": "",
      "AddressLine3": "",
      "PostCode": "",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "25/05/2017",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": null,
      "Latitude": null,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 689175,
      "LocalAuthorityBusinessID": "C1_PI_000033598",
      "BusinessName": "Mylor Stores",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "37 Lemon Hill",
      "AddressLine2": "Mylor Bridge",
      "AddressLine3": "Falmouth",
      "PostCode": "TR11 5NA",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "19/02/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.076441,
      "Latitude": 50.185213,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1070804,
      "LocalAuthorityBusinessID": "CP18_000675",
      "BusinessName": "Navy Inn",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "Queen Street",
      "AddressLine2": "Penzance",
      "AddressLine3": "Cornwall",
      "PostCode": "TR18 4DE",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "20/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 5,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.535819,
      "Latitude": 50.114994,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1087188,
      "LocalAuthorityBusinessID": "CP18_000879",
      "BusinessName": "Newquays Meals On Wheels Service-Home Caterer",
      "BusinessType": "Other catering premises",
      "BusinessTypeID": 7841,
      "AddressLine1": "",
      "AddressLine2": "",
      "AddressLine3": "",
      "PostCode": "",
      "RatingValue": 0,
      "RatingKey": "fhrs_0_en-GB",
      "RatingDate": "29/11/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 20,
      "Structural": 15,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": null,
      "Latitude": null,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1045887,
      "LocalAuthorityBusinessID": "CP18_000267",
      "BusinessName": "Off The Path Coffee Co",
      "BusinessType": "Mobile caterer",
      "BusinessTypeID": 7846,
      "AddressLine1": "Menalhyl Yard",
      "AddressLine2": "Mawgan Porth",
      "AddressLine3": "Newquay",
      "PostCode": "TR8 4BG",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "24/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 20,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.014691,
      "Latitude": 50.461612,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 657191,
      "LocalAuthorityBusinessID": "E1_8732",
      "BusinessName": "Pasty Presto",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Presto Retail Ltd",
      "AddressLine2": "2 Mill Square",
      "AddressLine3": "Padstow",
      "PostCode": "PL28 8AE",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "02/10/2017",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.93879509,
      "Latitude": 50.54180527,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1025056,
      "LocalAuthorityBusinessID": "CP18_000008",
      "BusinessName": "Peking Garden",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "New Peking Garden",
      "AddressLine2": "Fore Street",
      "AddressLine3": "East Looe",
      "PostCode": "PL13 1AD",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "11/12/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 15,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.453876019,
      "Latitude": 50.35419846,
      "AddressLine4": "Looe",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 402712,
      "LocalAuthorityBusinessID": "W2_00003234",
      "BusinessName": "Penmorvah Manor Hotel",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "Penjerrick Hill",
      "AddressLine2": "Budock Water",
      "AddressLine3": "Falmouth",
      "PostCode": "TR11 5ED",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "07/03/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.105975,
      "Latitude": 50.136855,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 860840,
      "LocalAuthorityBusinessID": "CP15_001060",
      "BusinessName": "Pennys Pies",
      "BusinessType": "Other catering premises",
      "BusinessTypeID": 7841,
      "AddressLine1": "",
      "AddressLine2": "",
      "AddressLine3": "",
      "PostCode": "",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "31/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": null,
      "Latitude": null,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 785626,
      "LocalAuthorityBusinessID": "CP15_000786",
      "BusinessName": "Perranwell Post Office And Stores",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Perranwell Post Office",
      "AddressLine2": "Perranwell Station",
      "AddressLine3": "Truro",
      "PostCode": "TR3 7PP",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "31/07/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.118155,
      "Latitude": 50.212589,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1076160,
      "LocalAuthorityBusinessID": "CP18_000755",
      "BusinessName": "Pizza Shop",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "2 Polmorla Road",
      "AddressLine2": "Wadebridge",
      "AddressLine3": "Cornwall",
      "PostCode": "PL27 7NB",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "01/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 5,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.837125,
      "Latitude": 50.515796,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 802157,
      "LocalAuthorityBusinessID": "CP15_000574",
      "BusinessName": "Prawn On The Lawn",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "Fusion",
      "AddressLine2": "11 Duke Street",
      "AddressLine3": "Padstow",
      "PostCode": "PL28 8AB",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "02/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 5,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.93951,
      "Latitude": 50.541732,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1031305,
      "LocalAuthorityBusinessID": "CP18_000091",
      "BusinessName": "Red Lantern Chinese Restaurant",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "5 - 7 Southgate Street",
      "AddressLine2": "Launceston",
      "AddressLine3": "Cornwall",
      "PostCode": "PL15 9DP",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "25/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.359922,
      "Latitude": 50.636771,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1087205,
      "LocalAuthorityBusinessID": "CP18_000897",
      "BusinessName": "Reef's Newquay",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "42 East Street",
      "AddressLine2": "Newquay",
      "AddressLine3": "Cornwall",
      "PostCode": "TR7 1BE",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "31/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.078973,
      "Latitude": 50.413798,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 551154,
      "LocalAuthorityBusinessID": "C1_PI_000046156",
      "BusinessName": "Rising Sun Hotel",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "The Square",
      "AddressLine2": "St Mawes",
      "AddressLine3": "Truro",
      "PostCode": "TR2 5DJ",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "24/01/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 5,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.013642,
      "Latitude": 50.159567,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 642038,
      "LocalAuthorityBusinessID": "CP12_000826",
      "BusinessName": "Rock Fish",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "1 Azime Court",
      "AddressLine2": "Rock Road",
      "AddressLine3": "Rock",
      "PostCode": "PL27 6NW",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "05/09/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.903339,
      "Latitude": 50.549441,
      "AddressLine4": "Wadebridge",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 750960,
      "LocalAuthorityBusinessID": "CP15_000325",
      "BusinessName": "Rock Pool Bar And Restaurant",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "The Rockpool",
      "AddressLine2": "1 Godrevy Towans",
      "AddressLine3": "Gwithian",
      "PostCode": "TR27 5ED",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "18/09/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.388051987,
      "Latitude": 50.23041916,
      "AddressLine4": "Hayle",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 565489,
      "LocalAuthorityBusinessID": "C1_PI_000032941",
      "BusinessName": "Royal Standard Inn",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "1 St Peters Road",
      "AddressLine2": "Flushing",
      "AddressLine3": "Falmouth",
      "PostCode": "TR11 5TP",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "16/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.070695,
      "Latitude": 50.165106,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 516179,
      "LocalAuthorityBusinessID": "W2_00002940",
      "BusinessName": "Sandbar Ltd",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "The Sand Bar",
      "AddressLine2": "Sydney Cove",
      "AddressLine3": "Praa Sands",
      "PostCode": "TR20 9TQ",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "07/09/2017",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.390909,
      "Latitude": 50.105809,
      "AddressLine4": "Penzance",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1101839,
      "LocalAuthorityBusinessID": "CP19_000075",
      "BusinessName": "Saturday Soup (All Saints Church)",
      "BusinessType": "Other catering premises",
      "BusinessTypeID": 7841,
      "AddressLine1": "All Saints Parish Church",
      "AddressLine2": "Killigrew Street",
      "AddressLine3": "Falmouth",
      "PostCode": "TR11 3PY",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "13/03/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.0767444,
      "Latitude": 50.1512085,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 557621,
      "LocalAuthorityBusinessID": "CP13_000622",
      "BusinessName": "Ship Inn",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "1 Fore Street",
      "AddressLine2": "Mevagissey",
      "AddressLine3": "St Austell",
      "PostCode": "PL26 6UQ",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "05/06/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 5,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.787586,
      "Latitude": 50.269924,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 402489,
      "LocalAuthorityBusinessID": "E1_9778",
      "BusinessName": "Smugglers",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "Smugglers Rest Cafe",
      "AddressLine2": "High Street",
      "AddressLine3": "Delabole",
      "PostCode": "PL33 9AD",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "06/06/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.7273158,
      "Latitude": 50.6273628,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 517238,
      "LocalAuthorityBusinessID": "C2_226844",
      "BusinessName": "Spar",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "3 Chester Road",
      "AddressLine2": "Newquay",
      "AddressLine3": "Cornwall",
      "PostCode": "TR7 2RT",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "24/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.06462,
      "Latitude": 50.41738,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 900903,
      "LocalAuthorityBusinessID": "E1_6338",
      "BusinessName": "Spar",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Camelford Stores",
      "AddressLine2": "13 - 15 Market Place",
      "AddressLine3": "Camelford",
      "PostCode": "PL32 9PA",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "22/03/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 5,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.678684235,
      "Latitude": 50.62284851,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 493774,
      "LocalAuthorityBusinessID": "C1_PI_000025902",
      "BusinessName": "Spar",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Spar Stores",
      "AddressLine2": "Smithy Lane",
      "AddressLine3": "Carnon Downs",
      "PostCode": "TR3 6HW",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "01/02/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.090081,
      "Latitude": 50.221985,
      "AddressLine4": "Truro",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 905970,
      "LocalAuthorityBusinessID": "CP16_000626",
      "BusinessName": "Sportsmans Arms",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "Bolitho Road",
      "AddressLine2": "Heamoor",
      "AddressLine3": "Penzance",
      "PostCode": "TR18 3EH",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "27/03/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.552689,
      "Latitude": 50.128361,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 459849,
      "LocalAuthorityBusinessID": "E1_51052",
      "BusinessName": "St Moritz Hotel",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "Trebetherick",
      "AddressLine2": "Wadebridge",
      "AddressLine3": "Cornwall",
      "PostCode": "PL27 6SD",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "18/02/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.920587,
      "Latitude": 50.56763,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1076154,
      "LocalAuthorityBusinessID": "CP18_000749",
      "BusinessName": "Tan And Mor",
      "BusinessType": "Mobile caterer",
      "BusinessTypeID": 7846,
      "AddressLine1": "",
      "AddressLine2": "",
      "AddressLine3": "",
      "PostCode": "",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "24/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 15,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": null,
      "Latitude": null,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 586932,
      "LocalAuthorityBusinessID": "CP12_001435",
      "BusinessName": "Tanyas",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "Hunger Angels Trust",
      "AddressLine2": "Four Winds",
      "AddressLine3": "Bodmin",
      "PostCode": "PL30 4HH",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "25/03/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 15,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.664859,
      "Latitude": 50.507835,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1029816,
      "LocalAuthorityBusinessID": "CP18_000077",
      "BusinessName": "Tasty Pasties",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "4 Princes Street",
      "AddressLine2": "Bude",
      "AddressLine3": "Cornwall",
      "PostCode": "EX23 8AT",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "10/01/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.544836,
      "Latitude": 50.83159,
      "AddressLine4": "",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 949062,
      "LocalAuthorityBusinessID": "CP17_000148",
      "BusinessName": "The Chippy",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "2 The Square",
      "AddressLine2": "Praze An Beeble",
      "AddressLine3": "Camborne",
      "PostCode": "TR14 0JR",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "01/11/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.311575,
      "Latitude": 50.173739,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1008343,
      "LocalAuthorityBusinessID": "CP17_000784",
      "BusinessName": "The Coldstreamer",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "The Coldstreamer Inn",
      "AddressLine2": "Gulval",
      "AddressLine3": "Penzance",
      "PostCode": "TR18 3BB",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "10/04/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.521863,
      "Latitude": 50.132234,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1087198,
      "LocalAuthorityBusinessID": "CP18_000889",
      "BusinessName": "The Corner Deli",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "12 Fore Street",
      "AddressLine2": "Porthleven",
      "AddressLine3": "Helston",
      "PostCode": "TR13 9HQ",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "11/02/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.315777,
      "Latitude": 50.085734,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 879079,
      "LocalAuthorityBusinessID": "CP16_000340",
      "BusinessName": "The Cornishman Inn",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "The Cornishman",
      "AddressLine2": "Fore Street",
      "AddressLine3": "Tintagel",
      "PostCode": "PL34 0DB",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "08/01/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.750927,
      "Latitude": 50.663098,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 959774,
      "LocalAuthorityBusinessID": "CP17_000294",
      "BusinessName": "The Fishermans Arms",
      "BusinessType": "Pub/bar/nightclub",
      "BusinessTypeID": 7843,
      "AddressLine1": "Fishermans Arms Inn",
      "AddressLine2": "Fore Street",
      "AddressLine3": "Newlyn",
      "PostCode": "TR18 5JR",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "18/06/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.546639,
      "Latitude": 50.101628,
      "AddressLine4": "Penzance",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1076181,
      "LocalAuthorityBusinessID": "CP18_000777",
      "BusinessName": "The Juice Box",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "Juice Bar",
      "AddressLine2": "Towan Promenade",
      "AddressLine3": "Newquay",
      "PostCode": "TR7 1DU",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "23/08/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.083743095,
      "Latitude": 50.4148407,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 669638,
      "LocalAuthorityBusinessID": "CP14_000609",
      "BusinessName": "The Old Inn",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "Churchtown",
      "AddressLine2": "Mullion",
      "AddressLine3": "Helston",
      "PostCode": "TR12 7HN",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "24/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 15,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.242758,
      "Latitude": 50.027254,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1070824,
      "LocalAuthorityBusinessID": "CP18_000696",
      "BusinessName": "The Pier",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "Pier Cafe",
      "AddressLine2": "Prince Of Wales Pier",
      "AddressLine3": "Falmouth",
      "PostCode": "TR11 3DF",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "26/11/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.070771,
      "Latitude": 50.156459,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 937269,
      "LocalAuthorityBusinessID": "CP16_001006",
      "BusinessName": "The Slipway Hotel",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "Slipway Hotel",
      "AddressLine2": "1 Church Hill",
      "AddressLine3": "Port Isaac",
      "PostCode": "PL29 3RQ",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "10/10/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.831893,
      "Latitude": 50.591428,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 516166,
      "LocalAuthorityBusinessID": "E1_6899",
      "BusinessName": "The Tasty Plaice",
      "BusinessType": "Takeaway/sandwich shop",
      "BusinessTypeID": 7844,
      "AddressLine1": "The Tasty Place",
      "AddressLine2": "16 Queen Street",
      "AddressLine3": "Bude",
      "PostCode": "EX23 8BB",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "18/01/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 15,
      "Structural": 10,
      "ConfidenceInManagement": 5,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.543840885,
      "Latitude": 50.83079147,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 516177,
      "LocalAuthorityBusinessID": "W2_00001794",
      "BusinessName": "The Witchball",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "Witchball Restaurant",
      "AddressLine2": "The Lizard",
      "AddressLine3": "Helston",
      "PostCode": "TR12 7NJ",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "28/02/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.203811,
      "Latitude": 49.968107,
      "AddressLine4": "Cornwall",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 1010104,
      "LocalAuthorityBusinessID": "CP17_000835",
      "BusinessName": "Trencreek Cafe",
      "BusinessType": "Restaurant/Cafe/Canteen",
      "BusinessTypeID": 1,
      "AddressLine1": "Trencreek Holiday Park Cafe",
      "AddressLine2": "Trencreek Holiday Park",
      "AddressLine3": "Trencreek Road",
      "PostCode": "TR8 4NS",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "31/07/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.056555,
      "Latitude": 50.406932,
      "AddressLine4": "Trencreek",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 813304,
      "LocalAuthorityBusinessID": "CP15_001014",
      "BusinessName": "Veryan Portloe Stores And Post Office",
      "BusinessType": "Retailers - other",
      "BusinessTypeID": 4613,
      "AddressLine1": "Roseland Supply Stores",
      "AddressLine2": "Century Lane",
      "AddressLine3": "Veryan",
      "PostCode": "TR2 5QA",
      "RatingValue": 1,
      "RatingKey": "fhrs_1_en-GB",
      "RatingDate": "26/02/2019",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 5,
      "Structural": 10,
      "ConfidenceInManagement": 20,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -4.922848,
      "Latitude": 50.218724,
      "AddressLine4": "Truro",
      "RightToReply": ""
    },
    {
      "ExtractDate": "01/06/2019",
      "ItemCount": 4638,
      "ReturnCode": "Success",
      "FHRSID": 609783,
      "LocalAuthorityBusinessID": "C2_220034",
      "BusinessName": "Victoria Hotel",
      "BusinessType": "Hotel/bed & breakfast/guest house",
      "BusinessTypeID": 7842,
      "AddressLine1": "East Street",
      "AddressLine2": "Newquay",
      "AddressLine3": "Cornwall",
      "PostCode": "TR7 1DB",
      "RatingValue": 2,
      "RatingKey": "fhrs_2_en-GB",
      "RatingDate": "10/04/2018",
      "LocalAuthorityCode": 705,
      "LocalAuthorityName": "Cornwall",
      "LocalAuthorityWebSite": "http://www.cornwall.gov.uk",
      "LocalAuthorityEmailAddress": "publicprotection@cornwall.gov.uk",
      "Hygiene": 10,
      "Structural": 15,
      "ConfidenceInManagement": 10,
      "SchemeType": "FHRS",
      "NewRatingPending": false,
      "Longitude": -5.078763,
      "Latitude": 50.414677,
      "AddressLine4": "",
      "RightToReply": ""
    }
];